# Hora de Colocar a Mão na Massa com NumPy

## 1. Básico

1. Crie um numpy array **np_alturas** a partir da lista **alturas** que contém a altura de alguns jogadores de futebol em centímetros.

In [96]:
import numpy as np

In [97]:
alturas = [180, 215, 210, 210, 188, 176, 209, 200]

In [98]:
np_alturas = np.array(alturas)

2. Mostre o array numpy **np_alturas** e verifique o resultado.

In [99]:
np_alturas

array([180, 215, 210, 210, 188, 176, 209, 200])

3. Crie um array numpy **np_altura_em_metros** com as alturas dos jogadores convertidas para metros.

In [100]:
np_altura_em_metros = np_alturas / 100

4. Mostre o array numpy **np_altura_em_metros** e verifique o resultado.

In [101]:
np_altura_em_metros

array([1.8 , 2.15, 2.1 , 2.1 , 1.88, 1.76, 2.09, 2.  ])

5. Crie um numpy array **np_pesos** a partir da lista **pesos** que contém a altura de alguns jogadores de futebol em gramas.

In [102]:
pesos = [64000, 73500, 67800, 89000, 98000, 76800, 78600, 82300]

6. Mostre o array numpy **np_pesos** e verifique o resultado.

In [103]:
np_pesos = np.array(pesos)
np_pesos

array([64000, 73500, 67800, 89000, 98000, 76800, 78600, 82300])

7. Crie um array numpy **np_pesos_em_kilos** com as alturas dos jogadores convertidas para kilos.

In [104]:
np_pesos_em_kilos = np_pesos / 1000

8. Mostre o array numpy **np_pesos_em_kilos** e verifique o resultado.

In [105]:
np_pesos_em_kilos

array([64. , 73.5, 67.8, 89. , 98. , 76.8, 78.6, 82.3])

9. Calcule os IMCs dos jogadores e armazene-os no array numpy **np_imcs**. 

In [106]:
np_imcs = np_pesos_em_kilos / np_altura_em_metros ** 2

10. Mostre o array **np_imcs** e verifique o resultado.

In [107]:
np_imcs

array([19.75308642, 15.90048675, 15.37414966, 20.1814059 , 27.7274785 ,
       24.79338843, 17.99409354, 20.575     ])

11. Mostre as dimensões dos arrays **np_alturas**, **np_pesos** e **np_imcs**.

In [108]:
np_alturas.shape

(8,)

In [109]:
np_pesos.shape

(8,)

In [110]:
np_imcs.shape

(8,)

## 2. Fatiamento

12. Mostre todos os ICMs acima de 21 no array **np_imcs**.

In [111]:
np_imcs[np_imcs > 21]

array([27.7274785 , 24.79338843])

13. Mostre o quarto ICMC do array **np_imcs**.

In [112]:
np_imcs[3]

20.181405895691608

14. Imprime do primeiro ao quarto imc do array **np_imcs**

In [113]:
np_imcs[:4]

array([19.75308642, 15.90048675, 15.37414966, 20.1814059 ])

## 3. Matrizes bidimensionais

15. Crie um array multidimensial **np_alturas_e_pesos** a partir da lista **alturas_e_pesos**.

In [137]:
alturas_e_pesos = [[180, 78400],
                   [215, 102700],
                   [210, 98500],
                   [188, 75200]]


In [138]:
np_alturas_e_pesos = np.array(alturas_e_pesos)
np_alturas_e_pesos

array([[   180,  78400],
       [   215, 102700],
       [   210,  98500],
       [   188,  75200]])

16. Mostre as dimensões ao array **np_alturas_e_pesos**.

In [139]:
np_alturas_e_pesos.shape

(4, 2)

17. Mostre o segundo elemento do array **np_alturas_e_pesos**.

In [140]:
np_alturas_e_pesos[0, 1]

78400

18. Selecione o segunda coluna do array np_alturas_e_pessos e armazene-a no array **np_pesos**

In [141]:
np_pesos = np_alturas_e_pesos[:,1]
np_pesos

array([ 78400, 102700,  98500,  75200])

19. Inclua a lista **atualizacao** no array **np_alturas_e_pesos_atualizado**

In [148]:
atualizacao = [[173, 64500],
              [164, 58600],
              [180, 89100]]

#np_atualizacao = np.array(atualizacao)

#np_alturas_e_pesos_atualizado = np.append(np_alturas_e_pesos, np_atualizacao, axis = 0)

np_alturas_e_pesos_atualizado = np.append(np_alturas_e_pesos, atualizacao, axis = 0)

In [149]:
np_alturas_e_pesos

array([[   180,  78400],
       [   215, 102700],
       [   210,  98500],
       [   188,  75200]])

In [150]:
np_alturas_e_pesos_atualizado

array([[   180,  78400],
       [   215, 102700],
       [   210,  98500],
       [   188,  75200],
       [   173,  64500],
       [   164,  58600],
       [   180,  89100]])

In [131]:
np_alturas_e_pesos_atualizados.shape

(7, 2)

20. Converte as alturas e os pesos do array **np_alturas_e_pesos_atualizado** para metros e kilos respectivamente e armazene o resultado no **np_alturas_e_pesos_convertido**. Ao final mostre as dimensões do array criado.

In [120]:
np_alturas_e_pesos_convertido = np_alturas_e_pesos_atualizados / [100, 1000]
np_alturas_e_pesos_convertido

array([[  1.8 ,  78.4 ],
       [  2.15, 102.7 ],
       [  2.1 ,  98.5 ],
       [  1.88,  75.2 ],
       [  1.73,  64.5 ],
       [  1.64,  58.6 ],
       [  1.8 ,  89.1 ]])

## 4. Estatística Básica

21. Mostre a média, a mediana e o desvio padrão das alturas e dos pesos do array **np_alturas_e_pesos_convertido**. Além disto investigue a correlação entre as alturas e os pesos.

In [121]:
#media alturas
np.mean(np_alturas_e_pesos_convertido[:,0])

1.8714285714285717

In [122]:
#media pesos
np.mean(np_alturas_e_pesos_convertido[:,1])

81.0

In [123]:
#mediana alturas
np.median(np_alturas_e_pesos_convertido[:,0])

1.8

In [124]:
#mediana pesos
np.median(np_alturas_e_pesos_convertido[:,1])

78.4

In [125]:
#desvio padrão alturas
np.std(np_alturas_e_pesos_convertido[:,0])

0.17471843237691007

In [126]:
#desvio padrão pesos
np.std(np_alturas_e_pesos_convertido[:,1])

15.386264746751982

In [151]:
#correlaçã entre alturas e pesos
np.corrcoef(np_alturas_e_pesos_convertido[:,0], np_alturas_e_pesos_convertido[:, 1])

array([[1.        , 0.90977457],
       [0.90977457, 1.        ]])